services:
  app:
    build: .
    container_name: nex_booking
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://postgres:neutro123*@postgresdb:5432/nex_booking_db"
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgresdb
    restart: always

  postgresdb:
    image: postgres:16
    container_name: nex_booking_db
    environment:
      POSTGRES_DB: nex_booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: neutro123*
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
